CONFIG_WIFI_NRF71=y
CONFIG_NRF71_P2P_MODE=y
CONFIG_NRF71_AP_MODE=y
CONFIG_NRF71_RX_NUM_BUFS=16
CONFIG_NRF_WIFI_DATA_HEAP_SIZE=200000
# Required by "nrf71 util heap" command (CONFIG_NRF71_UTIL)
CONFIG_SYS_HEAP_RUNTIME_STATS=y
CONFIG_NRF_WIFI_USE_KMU=y